
export const projectsList = [
    {
        projectID: 0,
        projectName: 'Portfolio',
        projectDescription: 'I chose React for this project as I am a huge fan of the tech and ease in developing stand-alone components. As for the design, I wanted to go for something modern and simple.',
        projectTechStack: 'React, HTML & CSS.',
        projectRepo: 'https://github.com/CarlWiren90/portfolio.git',
        projectDemoURL: '',
        projectImg: './projects/design-5.avif',
        projectImgDesktop: '',
        projectImgMobile: '',
    }, 
    {
        projectID: 1,
        projectName: 'Test',
        projectDescription: 'I chose React for this project as I am a huge fan of the aspect and ease in developing stand-alone components. As for the design, I wanted to go for something modern, simple yet elegant.',
        projectTechStack: 'React, HTML & CSS.',
        projectRepo: '',
        projectDemoURL: '',
        projectImg: './projects/design-5.avif',
        projectImgDesktop: '',
        projectImgMobile: '',
    },
    {
        projectID: 2,
        projectName: 'Test',
        projectDescription: 'I chose React for this project as I am a huge fan of the aspect and ease in developing stand-alone components. As for the design, I wanted to go for something modern, simple yet elegant.',
        projectTechStack: 'React, HTML & CSS.',
        projectRepo: '',
        projectDemoURL: '',
        projectImg: './projects/design-5.avif',
        projectImgDesktop: '',
        projectImgMobile: '',
    },
    {
        projectID: 3,
        projectName: 'Test',
        projectDescription: 'I chose React for this project as I am a huge fan of the aspect and ease in developing stand-alone components. As for the design, I wanted to go for something modern, simple yet elegant.',
        projectTechStack: 'React, HTML & CSS.',
        projectRepo: '',
        projectDemoURL: '',
        projectImg: './projects/design-5.avif',
        projectImgDesktop: '',
        projectImgMobile: '',
    }
]